version: '3.1'
services:
  db:
    image: postgres:12.2
    ports: ['5432:5432']
    environment:
      POSTGRES_PASSWORD: dev_password
      POSTGRES_USER: dev_user
      POSTGRES_DB: dev_db
  test-db:
    image: postgres:12.2
    ports: ['5433:5432']
    environment:
      POSTGRES_PASSWORD: dev_password
      POSTGRES_USER: dev_user
      POSTGRES_DB: dev_db
