---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: backend
  namespace: [[env]]
  labels:
    app: backend
    environment: [[env]]
spec:
  maxUnavailable: 30%
  selector:
    matchLabels:
      app: backend
