---

apiVersion: v1
kind: Service
metadata:
  name: cov-clear-backend
  namespace: [[env]]-cov-clear-backend
  labels:
    app: cov-clear-backend
    environment: [[env]]
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  selector:
    app: cov-clear-backend
