export const CREATE_NEW_ROLE = 'CREATE_NEW_ROLE';
export const CREATE_NEW_PERMISSION = 'CREATE_NEW_PERMISSION';
export const ASSIGN_ROLE_TO_USER = 'ASSIGN_ROLE_TO_USER';
export const ASSIGN_PERMISSION_TO_ROLE = 'ASSIGN_PERMISSION_TO_ROLE';
export const LIST_ROLES = 'LIST_ROLES';
export const LIST_PERMISSIONS = 'LIST_PERMISSIONS';
export const BULK_CREATE_USERS = 'BULK_CREATE_USERS';

export const CREATE_TEST_TYPE = 'CREATE_TEST_TYPE';

export const ADD_TAKE_HOME_TEST_RESULT = 'ADD_TAKE_HOME_TEST_RESULT';

export const ADMINISTER_TEST_WITH_HIGH_CONFIDENCE = 'ADMINISTER_TEST_WITH_HIGH_CONFIDENCE';
export const ADD_RESULTS_WITH_HIGH_CONFIDENCE = 'ADD_RESULTS_WITH_HIGH_CONFIDENCE';
