db:
  connectionUrl: DATABASE_URL

frontend:
  baseUrl: FRONTEND_BASE_URL

emailNotifier:
  mailGunConfig:
    apiKey: MAILGUN_API_KEY
    domain: MAILGUN_DOMAIN

i18n:
  defaultLanguage: DEFAULT_LANGUAGE

requirements:
  address: ADDRESS_REQUIRED

authentication:
  allowedMethods:
    magicLink: AUTH_MAGIC_LINK_ENABLED
    estonianId: AUTH_ESTONIAN_ID_ENABLED
  dokobit:
    accessToken: DOKOBIT_ACCESS_TOKEN

logLevels:
  messages: LOG_LEVEL_MESSAGES

jwt:
  secret: JWT_SECRET

port: PORT

rollbar:
  token: ROLLBAR_TOKEN

app:
  setupModeEnabled: APP_SETUP_MODE_ENABLED
