db:
  connectionUrl: DATABASE_URL

emailNotifier:
  mailGunConfig:
    apiKey: MAILGUN_API_KEY
    domain: MAILGUN_DOMAIN

jwt:
  secret: JWT_SECRET

port: PORT

rollbar:
  token: ROLLBAR_TOKEN

app:
  setupModeEnabled: APP_SETUP_MODE_ENABLED
