db:
  connectionUrl: DATABASE_URL

frontend:
  baseUrl: FRONTEND_BASE_URL

emailNotifier:
  mailGunConfig:
    apiKey: MAILGUN_API_KEY
    domain: MAILGUN_DOMAIN

i18n:
  defaultLanguage: DEFAULT_LANGUAGE

authentication:
  dokobit:
    accessToken: DOKOBIT_ACCESS_TOKEN

jwt:
  secret: JWT_SECRET

port: PORT

rollbar:
  token: ROLLBAR_TOKEN

app:
  setupModeEnabled: APP_SETUP_MODE_ENABLED
