db:
  connectionUrl: postgresql://dev_user:dev_password@localhost/dev_db

frontend:
  baseUrl: http://localhost:3000

emailNotifier:
  type: logging
  fromEmailHeader: no-reply@cov-clear.com
  mailGunConfig:
    apiKey: dummy
    domain: dummy

i18n:
  defaultLanguage: en

authentication:
  dokobit:
    accessToken: dummy
    baseUrl: https://id-sandbox.dokobit.com

logLevels:
  messages: info
  requests: warn

rollbar:
  token: dummy
  level: warning

jwt:
  timeToLiveInHours: 336
  secret: 1-9182fj1wofj1-08fj182fj1-90fj21-0r89j12-8rh

app:
  setupModeEnabled: false

port: 1337
