name: continuous-delivery
on:
  push:
    branches: ['master']
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: covclear/backend
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
  deploy-heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.0.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'cov-clear'
          heroku_email: 'igalarzab@gmail.com'
  deploy-eks:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-1
      EKS_CLUSTER_NAME: cov-clear-prod
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup kubeconfig
        run: aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
      - name: Deploy new UK version
        env:
          K8S_YAML_DIR: ./manifests
          IMAGE_TAG: sha-$(git rev-parse --short ${{ github.sha }})
          ROLE_ARN: arn:aws:iam::310398818202:role\\/cov-clear-uk-backend
          COUNTRY: uk
        run: |
          cd $K8S_YAML_DIR
          ./render_manifests.sh $COUNTRY $IMAGE_TAG $COUNTRY.cov-clear.com $ROLE_ARN | kc apply -f -
      - name: Deploy new EE version
        env:
          K8S_YAML_DIR: ./manifests
          IMAGE_TAG: sha-$(git rev-parse --short ${{ github.sha }})
          ROLE_ARN: arn:aws:iam::310398818202:role\\/cov-clear-ee-backend
          COUNTRY: ee
        run: |
          cd $K8S_YAML_DIR
          ./render_manifests.sh $COUNTRY $IMAGE_TAG $COUNTRY.cov-clear.com $ROLE_ARN | kc apply -f -
