name: test-and-deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.2
        ports: ['5433:5432']
        env:
          POSTGRES_PASSWORD: dev_password
          POSTGRES_USER: dev_user
          POSTGRES_DB: dev_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Cache NPM dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-cache-
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build
    - name: Run tests
      run: npm run test
      env:
        NODE_ENV: test
  upload-docker:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: covclear/backend
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
  deploy-production:
    runs-on: ubuntu-latest
    needs: [test, upload-docker]
    if: github.ref == 'refs/heads/master'
    env:
      AWS_REGION: eu-west-1
      EKS_CLUSTER_NAME: cov-clear
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup kubeconfig
        run: aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
      - name: Deploy UK environment
        env:
          K8S_YAML_DIR: ./manifests
          ROLE_ARN: arn:aws:iam::310398818202:role/cov-clear-uk-backend
          COUNTRY: uk
        run: |
          cd $K8S_YAML_DIR
          ./render_manifests.sh "$COUNTRY" "sha-$(git rev-parse --short ${{ github.sha }})" "$COUNTRY.cov-clear.com" "$ROLE_ARN" | kubectl apply -f -
          kubectl --namespace $COUNTRY rollout status deployments.apps/backend
      - name: Deploy EE environment
        env:
          K8S_YAML_DIR: ./manifests
          ROLE_ARN: arn:aws:iam::310398818202:role/cov-clear-ee-backend
          COUNTRY: ee
        run: |
          cd $K8S_YAML_DIR
          ./render_manifests.sh "$COUNTRY" "sha-$(git rev-parse --short ${{ github.sha }})" "$COUNTRY.cov-clear.com" "$ROLE_ARN" | kubectl apply -f -
          kubectl --namespace $COUNTRY rollout status deployments.apps/backend
